name = "digital-rights-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[vars]
JWT_SECRET = "your-secret-key"

[[d1_databases]]
binding = "DB"
database_name = "digital-rights-db"
database_id = "your-database-id" 