name = "digital-rights-api"
main = "src/index.ts"
compatibility_date = "2024-02-20"

[vars]
JWT_SECRET = "your-secret-key"

[[d1_databases]]
binding = "DB"
database_name = "digital-rights-db"
database_id = "" # You'll need to fill this in after creating the database 